### ISSUE TITLE
Reversing next work day

### ISSUE THREAD

**Issue by Eugerome** [ministryofjustice/govuk-bank-holidays#10]
Hey, using your library for some local council work. Need to find out the previous workday. Currently using the `is_work_day` method, but perhaps we could change up the `get_next_work_day` method to include a `step` param that we could set to -1 and iterate backwards? Something like this?

```
    def get_next_work_day(self, division=None, date=None, step=1):
        """
        Returns the next work day, skipping weekends and bank holidays
        NB: If no division is specified, only holidays common to *all* divisions are returned.
        :param division: see division constants; defaults to common holidays
        :param date: search starting from this date; defaults to today
        :param step: step, use -1 to reverse, default 1
        :return: datetime.date; NB: get_next_holiday returns a dict
        """
        date = date or datetime.date.today()
        one_day = datetime.timedelta(days=step)
        holidays = set(holiday['date'] for holiday in self.get_holidays(division=division))
        while True:
            date += one_day
            if date.weekday() not in self.weekend and date not in holidays:
                return date
```

Any thoughts?

**Comment by ushkarev** [comment]
good idea @Eugerome, going backwards in time sounds like a useful feature. i've added a `get_prev_work_day` method because i think it's more understandable than providing a negative step when asking for a _next_ day.
https://pypi.org/project/govuk-bank-holidays/0.9/

**Comment by Eugerome** [comment]
Sounds fair. Thanks for adding it!
