### ISSUE TITLE
Missing August Summer bank holiday

### ISSUE THREAD

**Issue by Geekiac** [ministryofjustice/govuk-bank-holidays#16]
The August Summer bank holiday appears to be missing.  Can you help?

**Comment by Geekiac** [comment]
Realised I need to set division!

**Comment by ushkarev** [comment]
Yeah, Government Digital Service, who provide the source data, structure it in such a way as to require selecting a "division". We felt it would be inappropriate to arbitrarily select England & Wales, for instance. The default action is to only present holidays common to _all_ divisions.
