### ISSUE TITLE
API suggestion

### ISSUE THREAD

**Issue by mdvthu** [ministryofjustice/govuk-bank-holidays#22]
Changing the BankHolidays class API would make it more natural to use the library to check if a date is a bank holiday:

```python
In [1]: import datetime
   ...: from govuk_bank_holidays.bank_holidays import BankHolidays
   ...: 
   ...: bank_holidays = BankHolidays()
   ...: datetime.date.fromisoformat('2023-12-25') in bank_holidays
Out[1]: True
```
Currently, you have to do something like this:

```python
In [2]: import datetime
   ...: from govuk_bank_holidays.bank_holidays import BankHolidays
   ...: 
   ...: bank_holidays = BankHolidays()
   ...: bank_holidays = [i['date'] for i in bank_holidays.get_holidays()]
   ...: datetime.date.fromisoformat('2023-12-25') in bank_holidays
Out[2]: True
```

**Comment by ushkarev** [comment]
does this not work for your use case?
```python
import datetime
from govuk_bank_holidays.bank_holidays import BankHolidays

bank_holidays = BankHolidays()
some_date = datetime.date.fromisoformat('2023-12-25')
bank_holidays.is_holiday(some_date)  # ←
```

**Comment by mdvthu** [comment]
I thought maybe `in` would be more idiomatic for Python, hence the suggestion, but no objection to using `is_holiday()`

**Comment by ushkarev** [comment]
if we think of `bank_holidays` as essentially a collection of dicts with a title, a date etc, i'm not super convinced that `date in bank_holiday` is idiomatic. one could argue that maybe `dict(date=…, title=…, etc) in bank_holiday` would be more expected? as in, it doesn't just contain a date but also the other attributes too? 🤔
