### ISSUE TITLE
missing 2 bank holidays?

### ISSUE THREAD

**Issue by jgunstone** [ministryofjustice/govuk-bank-holidays#23]
my understanding is that there are 8 bank holidays in a year? 

this package gives 6 

```py
>>> bank_holidays_2024 = [x for x in BankHolidays().get_holidays() if x["date"].year == 2024]
>>> len(bank_holidays_2024)
6
>>> [print(x["title"]) for x in bank_holidays_2024];
New Year’s Day
Good Friday
Early May bank holiday
Spring bank holiday
Christmas Day
Boxing Day
```

looks like:
- summer bank holiday
- easter monday

missing according to google ...?
![Image](https://github.com/user-attachments/assets/0876bbdb-80b3-42bd-a728-bba1fce44e52)

**Comment by ushkarev** [comment]
2 things!

while there is a cached file of bank holidays in the library, by default they are looked up from gov.uk:
https://github.com/ministryofjustice/govuk-bank-holidays/blob/main/README.rst?plain=1#L4-L8

you aren't specifying the `division` attribute so the dates coming back are common to _all_ parts of the UK:
https://github.com/ministryofjustice/govuk-bank-holidays/blob/main/README.rst?plain=1#L40-L41

e.g. summer bank holiday 26 aug in england, northern ireland and wales, but 5 aug in scotland

**Comment by jgunstone** [comment]
amazing - thanks!
