### ISSUE TITLE
Some holiday dates in 2019 for england and wales are incorrectly ignored when no division is specified

### ISSUE THREAD

**Issue by PeterAlabaster** [ministryofjustice/govuk-bank-holidays#4]
in get_holidays()
```
govuk_bank_holidays/bank_holidays.py:98
```
This line appears to be stripping dates which are scoped in the `england-and-wales` section which appear in the `.json` file, which results in this years holiday dates excluding some, such as `2019-04-22`.

Reproducable via:
```
import pprint
from govuk_bank_holidays.bank_holidays import BankHolidays
pprint.pprint([x['date'] for x in BankHolidays().get_holidays()]	)
```

Notice `2019-04-22` does not appear, along with some others which appear in the .json file.

If a division is specified, all dates show as expected:
```
import pprint
from govuk_bank_holidays.bank_holidays import BankHolidays
pprint.pprint([x['date'] for x in BankHolidays().get_holidays(division='england-and-wales')])
```

Seems that when the fallback is hit - additional code is run in the following block, and I can't quite figure out why / what it's supposed to be doing
```
        if division:
            holidays = self.data[division]
        else:
            holidays = self.data[self.ENGLAND_AND_WALES]
            dates_in_common = six.moves.reduce(
                set.intersection,
                (set(map(lambda holiday: holiday['date'], division_holidays))
                 for division, division_holidays in six.iteritems(self.data))
            )
            holidays = filter(lambda holiday: holiday['date'] in dates_in_common, holidays)
```

This would fix the issue, but may well cause others (that i'm not aware of)

```
        if division:
            holidays = self.data[division]
        else:
            holidays = self.data[self.ENGLAND_AND_WALES]
```

**Comment by ushkarev** [comment]
Hi @PeterAlabaster! Thanks for posting this issue… I didn’t even know anybody used this library :)

The idea is that if you *don’t* specify the `division` it only shows you holidays that are common to all parts of the UK. I don’t think defaulting to England and Wales would be the expected action.

Perhaps this needs better documentation?

**Comment by PeterAlabaster** [comment]
Hey @ushkarev , no problem. That explains the behaviour then! I think this issue will serve as sufficient documentation, unless you think otherwise.

Just found this repo today as https://pypi.org/project/holidays/ doesn't appear to work at all, and it does exactly what I need it to!

Quick question in terms of longevity - how is the `.json` file updated? Does it have to be manually maintained, and if so - is the data pulled from govuk? Only asking as the dates only go to 2020.

Thanks for the prompt response!

**Comment by ushkarev** [comment]
The library tries to load the JSON file from GOV.UK at initialisation (unless the `use_cached_holidays` is specified) so as long as GOV.UK keep updating the file, it should work! PS: The team I’m on use it for one of our projects so we keep an eye on it.
