### ISSUE TITLE
Dictionary Support

### ISSUE THREAD

**Issue by tomosdavies** [ministryofjustice/govuk-bank-holidays#7]
The command .get_holidays() provides a list of 42 dictionaries, but summer bank holidays aren't included in the list. Is there a reason for that?

**Comment by trave-uk** [comment]
England-and-Wales and Northern Ireland have a different date for the summer bank holiday to Scotland. If you don't supply a "division" when you call get_holidays, you only get a list of holidays shared between all regions of the UK, which will exclude these.
