### ISSUE TITLE
Docs don't state the scope of the library

### ISSUE THREAD

**Issue by rmetcalf9** [ministryofjustice/govuk-bank-holidays#8]
When choosing to use the library I need to know:
- What the valid date range is (through experiment dates past 2021 don't work, nor do dates before 2015 the docs should state this)
- Update policy for the library - will new version be released when new bank holidays are added
- It would be nice if I didn't have to check the code to work out that I can supply "cy" or "en" and what they mean. Also, example code for each division would be good.

**Comment by rmetcalf9** [comment]
Also it would be useful to know that when new years are added will old ones be removed or left there.

**Comment by ushkarev** [comment]
Hi @rmetcalf9

The read-me says that the library loads bank holidays from https://www.gov.uk/bank-holidays. It's up to the publishers of that website to decide what dates/years are available. You can subscribe to their calendar to know when they update official bank holiday lists. This library is designed to just be a convenience wrapper to their information.

As for localisation, you don't have to provide a language but you can choose to do so. It defaults to English and Welsh is the only other language available. As it happens, the Welsh translations have been taken from Google Translate so can't necessarily be trusted! The language codes are the standard ones you'd see whenever dealing with localisation in python and in most other libraries/frameworks ([ISO 639](https://en.wikipedia.org/wiki/ISO_639)).

If you'd like to improve the documentation, we'd welcome a pull request if it'd help others understand what's going on.

**Comment by ushkarev** [comment]
I've added a note to the read-me about the 2 languages available. Hopefully that'll help people?
